[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.26.1"
# CI backends to support
ci = "github"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
# Whether to install an updater program
install-updater = false
# Whether to enable GitHub Attestations
github-attestations = true
# The installers to generate for each app
installers = []
# Which actions to run on pull requests
pr-run-mode = "upload"

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-latest"
aarch64-unknown-linux-gnu = "buildjet-4vcpu-ubuntu-2204-arm"
x86_64-unknown-linux-gnu = "ubuntu-latest"
